// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1891.AerialAssist;
    
import edu.wpi.first.wpilibj.AnalogChannel;
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.bullbots.core.DualJaguar;
import org.bullbots.core.Winch;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput shooterloadSwitch;
    public static SpeedController shootershootMotor;
    public static DigitalInput shootershootSwitch;
    public static AnalogChannel shooterIRSensor2;
    public static AnalogChannel shooterIRSensor1;
    public static AnalogChannel shooterpotentiometer;
    public static SpeedController shooterangleMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static DualJaguar driveJags1,driveJags2;
    public static Winch winchJags ;
    
    public static void init() {
        
        
        
        driveJags1 = new DualJaguar(1, 2, 0.5, 0.0, 0.05);
        
        
        
        /*
        
        OLD CODE IS BELOW AND IS COMMENTED OUT... ABOVE IS FOR TESTING 
        
        */
        
        /*
        
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shooterloadSwitch = new DigitalInput(1, 7);
	LiveWindow.addSensor("Shooter", "loadSwitch", shooterloadSwitch);
        
        shootershootMotor = new Victor(1, 2);
	LiveWindow.addActuator("Shooter", "shootMotor", (Victor) shootershootMotor);
        
        shootershootSwitch = new DigitalInput(1, 6);
	LiveWindow.addSensor("Shooter", "shootSwitch", shootershootSwitch);
        
        shooterIRSensor2 = new AnalogChannel(1, 5);
	LiveWindow.addSensor("Shooter", "IRSensor2", shooterIRSensor2);
        
        shooterIRSensor1 = new AnalogChannel(1, 4);
	LiveWindow.addSensor("Shooter", "IRSensor1", shooterIRSensor1);
        
        shooterpotentiometer = new AnalogChannel(1, 3);
	LiveWindow.addSensor("Shooter", "potentiometer", shooterpotentiometer);
        
        shooterangleMotor = new Victor(1, 1);
	LiveWindow.addActuator("Shooter", "angleMotor", (Victor) shooterangleMotor);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
       
        
        driveJags1 = new DualJaguar(1, 2, 0.5, 0.0, 0.05);
        driveJags2 = new DualJaguar(6, 5, 0.5, 0.0, 0.05);
        winchJags = new Winch(3, 4, 0.5, 0.0, 0.05);
        
        // Adding components to the live window
        LiveWindow.addActuator("Drive Train", "Dual Jaguar 1", RobotMap.driveJags1);
        LiveWindow.addActuator("Drive Train", "Dual Jaguar 2", RobotMap.driveJags2);
        LiveWindow.addActuator("Winch", "Dual Jaguar 1", RobotMap.winchJags);
                
                
        */
    }
}
