// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc1891.AerialAssist.subsystems;
import edu.wpi.first.wpilibj.CANJaguar;
import org.usfirst.frc1891.AerialAssist.RobotMap;
import org.usfirst.frc1891.AerialAssist.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class DriveTrain {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
  
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void driveUsingVoltage(double leftValue, double rightValue) {
        RobotMap.driveJags1.driveUsingVoltage(leftValue);
        RobotMap.driveJags2.driveUsingVoltage(rightValue);
    }
    
    public void driveUsingSpeed(double leftValue, double rightValue) {
        RobotMap.driveJags1.driveUsingSpeed(leftValue);
        RobotMap.driveJags2.driveUsingSpeed(rightValue);
    }
    
    public void driveUsingPosition(double leftValue, double rightValue) {
        RobotMap.driveJags1.driveUsingPosition(leftValue);
        RobotMap.driveJags2.driveUsingPosition(rightValue);
    }
    
    public void driveUsingCurrent(double leftValue, double rightValue) {
        RobotMap.driveJags1.driveUsingCurrent(leftValue);
        RobotMap.driveJags2.driveUsingCurrent(rightValue);
    }
    
    public void stopDriving() {
       RobotMap.driveJags1.stop();
       RobotMap.driveJags2.stop();
    }
}
